plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 120

Layout/IndentationConsistency:
  EnforcedStyle: normal
  Enabled: true

Layout/IndentationWidth:
  Width: 2
  Enabled: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
  Enabled: true

Layout/DefEndAlignment:
  EnforcedStyleAlignWith: def
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'test/**/*'

Rails:
  Enabled: true
